import { WikiContent } from "../../models/wikiContent";
import { WikiId } from "../../enums/WikiId";
import { WikiCategory } from "../../enums/WikiCategory";
import { H2, Body } from "../../components/WikiPage";

const summary = (
  <p>
    Ploverky are large, ground-dwelling birds native to the forests and
    scrublands of Downunda. They are known for their distinctive nesting mounds,
    defensive aggression, and piercing vocalisations. They are widely regarded
    as pests due to their tendency to build mounds near human settlements.
  </p>
);

const content = (
  <>
    <H2>Description</H2>
    <Body>
      <p>
        Standing about one metre tall, ploverky have stocky bodies covered in
        black feathers with lighter underbellies. Their heads are bare and
        reddish, and both sexes possess multiple sharp spurs along their wings.
        Their call is a loud, shrill, horrifying scream that wards off most
        threats, even those much bigger than itself.
      </p>
    </Body>

    <H2>Habit</H2>
    <Body>
      <p>
        Ploverky inhabit forested regions, open woodlands, and occasionally
        urban fringes.
      </p>
    </Body>

    <H2>Diet</H2>
    <Body>
      <p>
        They are omnivorous, feeding on insects, seeds, fallen fruit, and
        carrion. They use their strong legs and beaks to dig through soil and
        leaf litter in search of food.
      </p>
    </Body>

    <H2>Behaviour</H2>
    <Body>
      <p>
        Ploverky are territorial and highly protective of their nesting mounds.
        During the breeding season, males construct large nesting mounds of
        soil, leaves, and debris that can reach three metres in height and up to
        fifteen metres across to attract females. Once a pair forms, both
        partners tend the mound, adjusting material to control temperature. The
        female lays multiple eggs at the top, which incubate through the heat
        generated by decomposing vegetation. Both parents remain on guard until
        the chicks hatch, after which the young are independent within days.
        They guard their mound aggressively, emitting loud screams and attacking
        intruders with their wing spurs. Their defensive behaviour and tendency
        to nest near roads, farms, and towns have led to frequent human
        conflict.
      </p>
    </Body>
  </>
);

export const Ploverky: WikiContent = {
  id: WikiId.Ploverky,
  category: WikiCategory.Fauna,
  title: "Ploverky",
  blurb:
    "Ploverky are large, ground-dwelling birds native to the forests and scrublands of Downunda.",
  summary,
  main: content,
};
