export enum ItemType {
  Accessory = "Accessory",
  Armour = "Armour",
  Clothing = "Clothing",
  ForceWeapon = "ForceWeapon",
  Concoction = "Concoction",
  Explosive = "Explosive",
  Food = "Food",
  Gear = "Gear",
  Gemstone = "Gemstone",
  Medical = "Medical",
  Poison = "Poison",
  RangedWeapon = "RangedWeapon",
  SlashWeapon = "SlashWeapon",
  Trap = "Trap",
}
