export enum SkillType {
  Agility = "Agility",
  Charisma = "Charisma",
  Dexterity = "Dexterity",
  Electric = "Electric",
  Intelligence = "Intelligence",
  Healing = "Healing",
  Kinetic = "Kinetic",
  Martial = "Martial",
  Nature = "Nature",
  Perception = "Perception",
  Psychic = "Psychic",
  Psychology = "Psychology",
  Pyro = "Pyro",
  Radiant = "Radiant",
  Sonic = "Sonic",
  Spirit = "Spirit",
  Stealth = "Stealth",
  Strength = "Strength",
  Toxic = "Toxic",
  Willpower = "Willpower",
}
