export enum SkillType {
  Strength = "Strength",
  Agility = "Agility",
  Dexterity = "Dexterity",
  Martial = "Martial",
  Throw = "Throw",
  Intelligence = "Intelligence",
  Nature = "Nature",
  Willpower = "Willpower",
  Charisma = "Charisma",
  Psychology = "Psychology",
  Stealth = "Stealth",
  Sight = "Sight",
  Hearing = "Hearing",
  Smell = "Smell",
  Pyro = "Pyro",
  Electric = "Electric",
  Kinetic = "Kinetic",
  Radiant = "Radiant",
  Sonic = "Sonic",
  Psychic = "Psychic",
  Toxic = "Toxic",
  Healing = "Healing",
  Spirit = "Spirit",
}
